<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_API Management and Testing</name>
   <tag></tag>
   <elementGuidId>5e8a9d8d-2175-468a-a58a-d6e173a33d28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#api-management-and-testing</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h2[@id='api-management-and-testing']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;API Management and TestingDirect link to API Management and Testing&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>466c1e05-3b04-4b38-8d8b-95f781a78a93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>anchor anchorWithStickyNavbar_LWe7</value>
      <webElementGuid>02d79b72-40b4-4854-9fc2-d67821559d9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>api-management-and-testing</value>
      <webElementGuid>37a332bd-ee03-4ba7-bebd-baf15a45a981</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>API Management and Testing​</value>
      <webElementGuid>75470e11-a8a2-4e05-a3df-74dffd421572</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;api-management-and-testing&quot;)</value>
      <webElementGuid>92059249-0ff1-49be-ac31-fa880994b80a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h2[@id='api-management-and-testing']</value>
      <webElementGuid>b6a5241a-c849-4578-9bcc-ec913d92961b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__docusaurus_skipToContent_fallback']/div/div/main/div/div/div/div/article/div/h2[8]</value>
      <webElementGuid>110048c6-1b3d-4378-87ed-1be747033c49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selenium Toolkit'])[1]/following::h2[1]</value>
      <webElementGuid>d73bfaee-f765-4e69-b295-2816302375ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QMetry'])[1]/following::h2[1]</value>
      <webElementGuid>ae744e5f-7a77-4e7b-8993-6848f0b9dd7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TIBCO'])[1]/preceding::h2[1]</value>
      <webElementGuid>9c590440-cba5-455d-9c7c-e3301eb23a69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='API Management and Testing']/parent::*</value>
      <webElementGuid>c19635a8-48ef-4b20-a5dc-be04058586c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2[8]</value>
      <webElementGuid>633028c7-86d1-4fce-99b9-a062585119bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[@id = 'api-management-and-testing' and (text() = 'API Management and Testing​' or . = 'API Management and Testing​')]</value>
      <webElementGuid>9821081f-4dca-4e6c-bddd-6fd8440cf379</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
