<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Accessibility</name>
   <tag></tag>
   <elementGuidId>5ba539c5-6fd9-4647-be51-530692a2c55c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#accessibility</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h2[@id='accessibility']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;AccessibilityDirect link to Accessibility&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>3e8e6dac-6ea1-4e7c-84fc-5cbecf66e9af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>anchor anchorWithStickyNavbar_LWe7</value>
      <webElementGuid>15cfc287-e028-4aae-91cb-4e851b2b3765</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>accessibility</value>
      <webElementGuid>c7284240-17fb-4a65-a4e5-b967983790dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Accessibility​</value>
      <webElementGuid>da681158-2bc6-45f6-9801-295089f8d0f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accessibility&quot;)</value>
      <webElementGuid>c088a1ea-7972-49ba-953a-463b76ef31ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h2[@id='accessibility']</value>
      <webElementGuid>29ed0efa-5c55-4221-a55d-e2992a2792d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__docusaurus_skipToContent_fallback']/div/div/main/div/div/div/div/article/div/h2[2]</value>
      <webElementGuid>0dc82fe1-ef8c-44a4-b2ef-4ae34c97be21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Harness'])[1]/following::h2[1]</value>
      <webElementGuid>585aa0b0-c87f-4e60-aa5e-ba64309be0b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TeamCity'])[1]/following::h2[1]</value>
      <webElementGuid>09ce7a71-a9c5-41bb-b980-6af0f8b6abf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='axe-core (by Deque)'])[1]/preceding::h2[1]</value>
      <webElementGuid>0e2f303a-9a88-4a88-98c2-abe9f1ee9ceb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2[2]</value>
      <webElementGuid>49e59e0c-cb64-4052-b2eb-e8397bfc4d0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[@id = 'accessibility' and (text() = 'Accessibility​' or . = 'Accessibility​')]</value>
      <webElementGuid>fa682d93-1701-4708-bc6a-ad70ae6c943d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
