<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Low-codeNo-codeModel-based Test Case Generation</name>
   <tag></tag>
   <elementGuidId>b5d55741-e8c7-4d0c-a405-ce331cc077d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#low-codeno-codemodel-based-test-case-generation</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h2[@id='low-codeno-codemodel-based-test-case-generation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Low-code/No-code/Model-based Test Case GenerationDirect link to Low-code/No-code/Model-based Test Case Generation&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>73400077-b165-4946-b395-8ed1329b34fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>anchor anchorWithStickyNavbar_LWe7</value>
      <webElementGuid>d61a6663-2974-4815-ba86-b73f3239f923</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>low-codeno-codemodel-based-test-case-generation</value>
      <webElementGuid>05527137-909f-4e0c-aa5f-603be43f2e9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Low-code/No-code/Model-based Test Case Generation​</value>
      <webElementGuid>4504d2e3-734d-47d2-b64a-95e43cb0af9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;low-codeno-codemodel-based-test-case-generation&quot;)</value>
      <webElementGuid>8bbbc429-0658-4073-a754-5c32e6c06a72</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h2[@id='low-codeno-codemodel-based-test-case-generation']</value>
      <webElementGuid>b3f5f704-9c7b-46a0-b02e-0336d91e3e86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__docusaurus_skipToContent_fallback']/div/div/main/div/div/div/div/article/div/h2[7]</value>
      <webElementGuid>77f13446-d6bc-4b9e-819d-9b454eadc466</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='K2View'])[1]/following::h2[1]</value>
      <webElementGuid>ec3482d3-a06b-48d9-ae97-930ee08a71b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GenRocket'])[1]/following::h2[1]</value>
      <webElementGuid>4dd7b90e-eac5-4dc1-b91a-7ad526c82698</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keysight Eggplant'])[1]/preceding::h2[1]</value>
      <webElementGuid>ddbcef70-4c3c-4b83-8026-3a42b5b64a51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Low-code/No-code/Model-based Test Case Generation']/parent::*</value>
      <webElementGuid>3f9d859a-ed13-4f75-ba67-8f00f7863c3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2[7]</value>
      <webElementGuid>fbf3cbf1-51a0-4a14-9183-2184c719ecbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[@id = 'low-codeno-codemodel-based-test-case-generation' and (text() = 'Low-code/No-code/Model-based Test Case Generation​' or . = 'Low-code/No-code/Model-based Test Case Generation​')]</value>
      <webElementGuid>14fed8fb-cee3-4b82-8d55-7a85c75bf6f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
