<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_4</name>
   <tag></tag>
   <elementGuidId>1856cc14-c697-4cba-ba1e-418188e6240d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='panel--tabs--0']/div/div/div/div/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr/td[4]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div._1xnkk5ra.notranslate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;NaN, Invalid date, Invalid date NaN. Niedostępne NaN, Invalid date, Invalid date NaN. Niedostępne NaN, Invalid date, Invalid date NaN. Niedostępne NaN, Invalid date, Invalid date NaN NaN, Invalid date, Invalid date NaN NaN, Invalid date, Invalid date NaN NaN, Invalid date, Invalid date NaN&quot;i] >> internal:label=&quot;NaN, Invalid date, Invalid date NaN&quot;s >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a3cc22ac-dc07-4317-b30d-627b76602a52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_1xnkk5ra notranslate</value>
      <webElementGuid>c932d978-89f8-48cc-8ad7-0960d5d8167b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>calendar-day-04.07.2024</value>
      <webElementGuid>de9354d5-0e67-49a3-95a0-4a1b68383eb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-is-day-blocked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ae3d4329-9c8a-41cc-a0f3-7921187ae73a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>cac89130-0a9e-447c-bba1-d34093b91164</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;panel--tabs--0&quot;)/div[@class=&quot;dioea41 atm_h_1h6ojuz__7pk1ck atm_9s_1txwivl__7pk1ck atm_ar_1bp4okc__7pk1ck atm_fc_1h6ojuz__7pk1ck dir dir-ltr&quot;]/div[@class=&quot;d1hw4v9n atm_e2_1osqo2v atm_j6_1665v6k dir dir-ltr&quot;]/div[@class=&quot;_g2s11rv&quot;]/div[1]/div[1]/div[@class=&quot;_14676s3&quot;]/div[@class=&quot;_1foj6yps&quot;]/div[@class=&quot;_2hyui6e&quot;]/div[@class=&quot;_1lds9wb&quot;]/div[@class=&quot;_ytfarf&quot;]/table[@class=&quot;_cvkwaj&quot;]/tbody[1]/tr[1]/td[@class=&quot;_1qvi71ld&quot;]/div[@class=&quot;_1xnkk5ra notranslate&quot;]</value>
      <webElementGuid>dee376a7-08fa-4e5a-9f43-4fb9ee39944a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='panel--tabs--0']/div/div/div/div/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr/td[4]/div</value>
      <webElementGuid>5a9cf483-b246-4bc3-a2b6-38c2aef31343</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lipiec 2024'])[1]/following::div[4]</value>
      <webElementGuid>ac1220c1-565e-4f6a-b53e-396551f88976</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Czerwiec 2024'])[1]/following::div[37]</value>
      <webElementGuid>b7706ec5-d65d-4920-a7fe-5e582f046302</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sierpień 2024'])[1]/preceding::div[28]</value>
      <webElementGuid>f9deec6c-3dcd-4847-9545-5ba5e1fe277c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wrzesień 2024'])[1]/preceding::div[62]</value>
      <webElementGuid>be8d3f38-c1bb-47a9-bd58-0ebb88952545</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/table/tbody/tr/td[4]/div</value>
      <webElementGuid>16f423b2-2ea4-4381-923c-68133f9c91e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '4' or . = '4')]</value>
      <webElementGuid>47be73b1-149c-48ae-bcf2-f86ad8bb0d30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
