<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_31</name>
   <tag></tag>
   <elementGuidId>fdf888b6-c211-45ab-8ee2-bb7aab4cf1e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='panel--tabs--0']/div/div/div/div/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr[5]/td[3]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td._12y48re1 > div._1f9mwmbh.notranslate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;NaN, Invalid date, Invalid date NaN NaN, Invalid date, Invalid date NaN NaN, Invalid date, Invalid date NaN&quot;s] >> internal:label=&quot;NaN, Invalid date, Invalid date NaN&quot;i >> nth=2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7b780bea-cf1b-4ac4-ab0e-b9b53c75a067</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_1f9mwmbh notranslate</value>
      <webElementGuid>aa75bc12-ae4d-488e-8664-d4f6cd7ec177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>calendar-day-31.07.2024</value>
      <webElementGuid>8bd57d87-9010-4fae-9ebf-6cea816a20e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-is-day-blocked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0f94a70d-97b0-4bdc-aeca-7e39de2d9643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>31</value>
      <webElementGuid>f20be2ae-6134-4b4a-abb8-1c18dcda26f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;panel--tabs--0&quot;)/div[@class=&quot;dioea41 atm_h_1h6ojuz__7pk1ck atm_9s_1txwivl__7pk1ck atm_ar_1bp4okc__7pk1ck atm_fc_1h6ojuz__7pk1ck dir dir-ltr&quot;]/div[@class=&quot;d1hw4v9n atm_e2_1osqo2v atm_j6_1665v6k dir dir-ltr&quot;]/div[@class=&quot;_g2s11rv&quot;]/div[1]/div[1]/div[@class=&quot;_14676s3&quot;]/div[@class=&quot;_1foj6yps&quot;]/div[@class=&quot;_2hyui6e&quot;]/div[@class=&quot;_1lds9wb&quot;]/div[@class=&quot;_ytfarf&quot;]/table[@class=&quot;_cvkwaj&quot;]/tbody[1]/tr[5]/td[@class=&quot;_12y48re1&quot;]/div[@class=&quot;_1f9mwmbh notranslate&quot;]</value>
      <webElementGuid>03a80b43-98d7-4ebf-b6ed-2a163b034fc8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='panel--tabs--0']/div/div/div/div/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr[5]/td[3]/div</value>
      <webElementGuid>a1cde7a3-e4e8-4e92-9790-7ff911aa524e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lipiec 2024'])[1]/following::div[31]</value>
      <webElementGuid>16c1f3ae-1338-4176-a47c-9152c515db56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Czerwiec 2024'])[1]/following::div[64]</value>
      <webElementGuid>adf0e7ba-22cd-4f25-920f-6e687c81dc4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sierpień 2024'])[1]/preceding::div[1]</value>
      <webElementGuid>2179bd24-8cb2-40fb-85c9-3852dd6eae12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wrzesień 2024'])[1]/preceding::div[35]</value>
      <webElementGuid>ffd43ce8-fa9d-424a-b574-7161b763e39d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='31']/parent::*</value>
      <webElementGuid>4de7a4e0-0a61-4b67-9747-189ed3116361</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/table/tbody/tr[5]/td[3]/div</value>
      <webElementGuid>c8edc43b-38d4-4550-8132-3c02efbbbfd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '31' or . = '31')]</value>
      <webElementGuid>9e32bb77-6d55-43e5-9ef6-6ab01279f6db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
