<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Accept All Cookies</name>
   <tag></tag>
   <elementGuidId>ecb1ffc0-2f80-4036-b0f9-18fd416ae722</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#onetrust-accept-btn-handler</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='onetrust-accept-btn-handler']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Accept All Cookies&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>395cd873-0e07-4de1-a61d-ba66ee80c1bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>onetrust-accept-btn-handler</value>
      <webElementGuid>b9692e85-023c-4b7b-a9a7-eaf9139dbb02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Accept All Cookies</value>
      <webElementGuid>317cbc24-5f48-4a63-8434-8269aaec5b57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;onetrust-accept-btn-handler&quot;)</value>
      <webElementGuid>c206b15b-39e9-4371-bee7-6cd4670c92bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='onetrust-accept-btn-handler']</value>
      <webElementGuid>27a02dae-3a86-4ad3-8c18-cf12d9aae28d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='onetrust-button-group']/div/button</value>
      <webElementGuid>09dc2479-ff34-4dea-bc8f-5bec2a160096</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cookie Notice.'])[1]/following::button[1]</value>
      <webElementGuid>ee3ea31b-3a3b-4349-a2ed-ae0da9b2373a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reject All'])[1]/preceding::button[1]</value>
      <webElementGuid>b95853f4-aec9-4003-b211-5995c005b871</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cookies Settings'])[2]/preceding::button[2]</value>
      <webElementGuid>ced9d302-7229-4471-9e1b-675f7f1b8701</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Accept All Cookies']/parent::*</value>
      <webElementGuid>784ff529-87d1-4a50-b5ab-f93d9e29cea9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/button</value>
      <webElementGuid>7f4a020e-e428-4160-aeb9-243e9037405a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'onetrust-accept-btn-handler' and (text() = 'Accept All Cookies' or . = 'Accept All Cookies')]</value>
      <webElementGuid>a29b5bd0-eb38-4bbd-bf38-3d4750636eb3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
